### ISSUE TITLE
Training/Testing R2

### ISSUE THREAD

**Issue by m-mews** [daiqile96/OTTERS#3]
Thank you for creating a wonderful pipeline! I ran the pipeline and obtained the weights for the individual methods. The testing R2 for the model was used for filtering the TWAS results; however, I'm struggling to find which script you used to calculate the predicted gene expression values using each method. I found the Summary_OTTERS_GReX.R script in the OTTERS_paper Github, but I do not see how you generated the Pred.GReX files. Thank you in advance for your assistance!

**Comment by daiqile96** [comment]
Thank you for pointing out this!

I used OTTERS/imputing.py to calculate the predicted gene expression values (see [here](https://github.com/daiqile96/OTTERS_paper/blob/main/real_data/eQTLGen_sumstats/Run_OTTERS_StageII.sh#L38-L50)).

To use imputing.py, you need to provide a list of samples for imputation. An example of this sample list can be found [here](https://raw.githubusercontent.com/daiqile96/OTTERS/main/Example/Exp_samples.txt). The first column is FID and the second column is IID from the PLINK sample information file (.fam file) of the samples that you want to predict. The example of using imputing.py can also be found in the last section of [example](https://raw.githubusercontent.com/daiqile96/OTTERS/main/Example/Exp_samples.txt).

Sorry for the confusion. Let me know if the imputing.py doesn't work for you.
