### ISSUE TITLE
Imputing Expression Error: Single SNP models

### ISSUE THREAD

**Issue by m-mews** [daiqile96/OTTERS#7]
I noticed when I was imputing the genetically regulated expression of my genes that I get an error saying "There is no estimated eQTL weights for [method]". However,  when I went back to my model weight file, there is a single SNP for that gene. Could you look into this issue? Thank you in advance!

num=0
TargetID=ENSG00000211970
There is no estimated eQTL weights for lsum
Done.

cat lsum.txt
CHROM   POS     A1      A2      TargetID        ES
14      106645480       C       T       ENSG00000211970 -0.0499000000000002

**Comment by daiqile96** [comment]
What's your input for the --models= parameter? The eQTL weights files are required to have the same names as the models. For example, for --model=lassosum, the eQTL weights file should be named as lassosum.txt.

**Comment by m-mews** [comment]
I had adjusted the modeling parameter to --models=['P0.001', 'P0.05', 'lsum', 'SDPR', 'PRScs']. Here's another example where each method has a single SNP and I receive the following output. Thank you in advance for looking into this issue!!!

num=0
TargetID=ENSG00000166321
There is no estimated eQTL weights for P0.001
There is no estimated eQTL weights for P0.05
There is no estimated eQTL weights for lsum
There is no estimated eQTL weights for SDPR
There is no estimated eQTL weights for PRScs
Done.

cat lsum.txt
CHROM   POS     A1      A2      TargetID        ES
10      73229583        G       T       ENSG00000166321 -0.7499

cat P0.001.txt
CHROM   POS     A1      A2      TargetID        ES
10      73229583        G       T       ENSG00000166321 -0.22962028

cat P0.05.txt
CHROM   POS     A1      A2      TargetID        ES
10      73229583        G       T       ENSG00000166321 -0.22962028

cat PRScs.txt
CHROM   POS     A1      A2      TargetID        ES
10      73229583        G       T       ENSG00000166321 -0.11472381529486128

cat SDPR.txt
CHROM   POS     A1      A2      TargetID        ES
10      73229583        G       T       ENSG00000166321 -0.229743

**Comment by daiqile96** [comment]
Thanks for the example! I used the tabix tool to extract the eQTL weights for each gene, and the first line was skipped, causing this error. I've fixed the bug and updated the OTTERS tool. Could you please try again and let me know if it works for you?

**Comment by m-mews** [comment]
Thank you so much!!! I re-ran the code and it works this time!
